{% set name = "cellcutter" %}
{% set version = "0.2.12" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8c3855ac754edb06efb7340ba9c5f26091e71be02252f662e90626333803de51

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  entry_points:
    - cut_cells=cellcutter.cli:cut
    - cut_tiles=cellcutter.cli:cut_tiles
  noarch: python

requirements:
  host:
    - pip
    - python>=3.8
  run:
    - python>=3.8
    - scikit-image
    - numpy
    - pandas
    - tifffile
    - zarr<=2.14.0
    - numcodecs

test:
  imports:
    - cellcutter.cli

about:
  home: https://github.com/labsyspharm/cellcutter
  license: MIT
  license_family: BSD
  summary: Create thumbnails of cells in a given image
