{% set name = "cellcutter" %}
{% set version = "0.2.13" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/py3/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}-py3-none-any.whl
  sha256: 4f87f123d674353fbb9e553e98d7274044ec1d70baa2b32af0c999dd74a7db25

build:
  number: 0
  script: "{{ PYTHON }} -m pip install {{ name }}-{{ version }}*.whl --no-deps --ignore-installed -vv"
  entry_points:
    - cut_cells=cellcutter.cli:cut
    - cut_tiles=cellcutter.cli:cut_tiles
  noarch: python

requirements:
  host:
    - pip
    - python>=3.11
    - setuptools
    - wheel
  run:
    - python>=3.11
    - scikit-image
    - numpy>=2
    - pandas
    - tifffile
    - zarr>=3.1.4
    - numcodecs

test:
  imports:
    - cellcutter.cli

about:
  home: https://github.com/labsyspharm/cellcutter
  license: MIT
  license_family: BSD
  summary: Create thumbnails of cells in a given image
